# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 4.4"

gem "jekyll-relative-links"

gem "jekyll-remote-theme"

gem "jekyll-avatar"

gem "jekyll-feed"

gem "jekyll-github-metadata"

gem "jekyll-include-cache"

gem "jekyll-seo-tag"
gem "jekyll-sitemap"
